apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgre-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  mountOptions:
  - hard
  - nfsvers=4.1
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 192.168.5.40
    path: /shared/postgree/
    #  hostPath:
#path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgre-pv-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
