apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-app-static-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  mountOptions:
  - hard
  - nfsvers=4.1
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 192.168.5.40
    path: /shared/django_app_static_vol
    #  hostPath:
#path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-app-static-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-app-media-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  mountOptions:
  - hard
  - nfsvers=4.1
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 192.168.5.40
    path: /shared/django_app_media_vol
    #  hostPath:
#path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-app-media-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
